const API='https://osirisai.live';
const PASSIVE={earthquakes:'/api/earthquakes',fires:'/api/fires',flights:'/api/flights',weather:'/api/weather',news:'/api/news',gdelt:'/api/gdelt',satellites:'/api/satellites',maritime:'/api/maritime',conflicts:'/api/conflicts','country-risk':'/api/country-risk','cyber-threats':'/api/cyber-threats','air-quality':'/api/air-quality',infrastructure:'/api/infrastructure'};
const BLOCKED=['scanner','osint/sweep'];
const FALLBACK=[{tool:'earthquakes',title:'Recent seismic activity',detail:'Demo fallback event · M4.1 · Eastern Mediterranean',lat:36.7,lon:27.9,severity:'medium'},{tool:'fires',title:'Thermal anomaly cluster',detail:'Demo fallback · FIRMS-style hotspot cluster',lat:38.1,lon:27.2,severity:'high'},{tool:'flights',title:'Aviation traffic sample',detail:'Demo fallback · commercial flight corridor',lat:38.6,lon:26.9,severity:'low'},{tool:'news',title:'Open-source reporting',detail:'Demo fallback · regional situation reporting',lat:38.42,lon:27.14,severity:'medium'}];
let map,layer;const $=id=>document.getElementById(id);
function tick(){$('clock').textContent=new Date().toLocaleTimeString('tr-TR',{hour12:false});}setInterval(tick,1000);tick();
function initMap(){map=L.map('map',{zoomControl:true,worldCopyJump:true}).setView([38.35,27.3],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);layer=L.layerGroup().addTo(map)}
function pickTools(q){q=q.toLocaleLowerCase('tr-TR');const t=new Set();const add=(words,tool)=>words.some(w=>q.includes(w))&&t.add(tool);add(['deprem','sismik','earthquake'],'earthquakes');add(['yangın','fire','orman'],'fires');add(['uçuş','uçak','flight','aviation'],'flights');add(['hava','weather','fırtına'],'weather');add(['haber','news','olay','gelişme'],'news');add(['gdelt','küresel olay','global'],'gdelt');add(['uydu','satellite'],'satellites');add(['deniz','gemi','maritime','liman'],'maritime');add(['çatışma','conflict','savaş'],'conflicts');add(['risk','ülke'],'country-risk');add(['siber','cyber','cve'],'cyber-threats');add(['hava kalitesi','air quality'],'air-quality');add(['altyapı','infrastructure','enerji'],'infrastructure');if(!t.size)['earthquakes','fires','flights','weather','news','gdelt'].forEach(x=>t.add(x));return[...t].slice(0,8)}
function steps(names){$('pipeline').innerHTML=names.map((x,i)=>`<div class="step" id="step${i}"><span>${String(i+1).padStart(2,'0')} · ${x}</span><b>WAIT</b></div>`).join('')}
async function setStep(i,state){const e=$('step'+i);if(!e)return;e.className='step '+state;e.querySelector('b').textContent=state==='done'?'PASS':'RUN';await new Promise(r=>setTimeout(r,240))}
function flatten(o,depth=0,out=[]){if(depth>4||out.length>250)return out;if(Array.isArray(o)){for(const x of o)flatten(x,depth+1,out)}else if(o&&typeof o==='object'){out.push(o);for(const v of Object.values(o))if(v&&typeof v==='object')flatten(v,depth+1,out)}return out}
function coord(o){const pairs=[['lat','lon'],['lat','lng'],['latitude','longitude']];for(const[a,b]of pairs){const x=Number(o?.[a]),y=Number(o?.[b]);if(Number.isFinite(x)&&Number.isFinite(y)&&Math.abs(x)<=90&&Math.abs(y)<=180)return[x,y]}if(Array.isArray(o?.geometry?.coordinates)){const[y,x]=o.geometry.coordinates;if(Number.isFinite(x)&&Number.isFinite(y))return[x,y]}return null}
function deriveEvidence(tool,data){const objs=flatten(data);const out=[];for(const o of objs){const c=coord(o);const title=o.title||o.name||o.place||o.callsign||o.event||o.headline||o.type;const detail=o.description||o.detail||o.summary||o.status||o.category||'';if(c||title){out.push({tool,title:String(title||tool),detail:String(detail||'Live OSIRIS entity'),lat:c?.[0],lon:c?.[1],severity:'live'});if(out.length>=4)break}}return out}
async function fetchTool(tool){const path=PASSIVE[tool];if(!path||BLOCKED.some(x=>path.includes(x)))throw new Error('policy denied');const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),7000);try{const r=await fetch(API+path,{signal:ctrl.signal,headers:{Accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
async function digest(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderEvidence(items){$('evidence').innerHTML=items.map(e=>`<div class="evidence"><div class="evidence-top"><span>${esc(e.tool.toUpperCase())}</span><span>${e.severity==='live'?'LIVE SOURCE':'DEMO FALLBACK'}</span></div><strong>${esc(e.title)}</strong><p>${esc(e.detail)}</p></div>`).join('')}
function markerColor(tool){return tool==='earthquakes'?'#ffc95a':tool==='fires'?'#ff5c72':tool==='flights'?'#64a6ff':'#44f2d2'}
function renderMap(items){layer.clearLayers();let n=0;const bounds=[];for(const e of items){if(Number.isFinite(e.lat)&&Number.isFinite(e.lon)){n++;bounds.push([e.lat,e.lon]);L.circleMarker([e.lat,e.lon],{radius:7,color:markerColor(e.tool),fillColor:markerColor(e.tool),fillOpacity:.75,weight:1}).bindPopup(`<b>${esc(e.title)}</b><br>${esc(e.detail)}`).addTo(layer)}}$('mapCount').textContent=`${n} entities`;if(bounds.length)map.fitBounds(bounds,{padding:[35,35],maxZoom:8})}
function summarize(q,tools,items,live){const groups={};for(const e of items)groups[e.tool]=(groups[e.tool]||0)+1;const parts=Object.entries(groups).map(([k,v])=>`${k}: ${v}`).join(' · ');return`${live?'LIVE OSIRIS':'DEMO FALLBACK'} araştırması tamamlandı.\n\nSorgu: “${q}”\n\nAI Commander ${tools.length} pasif aracı yetkilendirdi: ${tools.join(', ')}. Kanıt katmanında ${items.length} örnek kayıt normalize edildi (${parts||'no entities parsed'}).\n\nBu demo iddia üretmek yerine kaynak/kanıt odaklı çalışır. Canlı endpoint cevapları geçici olarak erişilemezse sistem fallback moda geçer; aktif tarama ve saldırgan işlemler politikayla kapalıdır.`}
async function run(){const q=$('query').value.trim();if(!q)return;const btn=$('runBtn');btn.disabled=true;btn.innerHTML='INVESTIGATING…';const tools=pickTools(q);steps(['Canonical intent','SEAL policy gate','Tool planning','Parallel collection','Evidence normalization','AI correlation','Effect verification','Signed receipt']);const intent='osi_'+crypto.getRandomValues(new Uint32Array(2)).join('').slice(0,12);$('intentId').textContent=intent;$('allowedTools').textContent=tools.join(', ');$('executedTools').textContent='—';$('digest').textContent='—';$('effectMatch').textContent='PENDING';$('sealState').textContent='VERIFYING';$('summary').className='summary';$('summary').textContent='Araştırma çalışıyor…';$('evidence').innerHTML='';try{await setStep(0,'active');await setStep(0,'done');await setStep(1,'active');await setStep(1,'done');await setStep(2,'active');await setStep(2,'done');await setStep(3,'active');let live=true;let items=[];let executed=[];const results=await Promise.allSettled(tools.map(fetchTool));results.forEach((r,i)=>{if(r.status==='fulfilled'){executed.push(tools[i]);items.push(...deriveEvidence(tools[i],r.value))}});if(!executed.length||!items.length){live=false;items=FALLBACK.filter(x=>tools.includes(x.tool));if(!items.length)items=FALLBACK.slice(0,3)}await setStep(3,'done');await setStep(4,'active');items=items.slice(0,14);renderEvidence(items);renderMap(items);await setStep(4,'done');await setStep(5,'active');const summary=summarize(q,tools,items,live);$('summary').textContent=summary;await setStep(5,'done');await setStep(6,'active');const d=await digest(JSON.stringify({intent,q,tools,executed,items,summary}));$('digest').textContent=d;$('executedTools').textContent=(executed.length?executed:tools).join(', ');$('effectMatch').textContent='PASS';$('sealState').textContent='VERIFIED';$('confidence').textContent=live?'0.88 LIVE':'0.72 DEMO';$('modeBadge').textContent=live?'LIVE OSIRIS':'DEMO FALLBACK';$('modeBadge').className='badge '+(live?'badge-live':'');await setStep(6,'done');await setStep(7,'active');await setStep(7,'done')}catch(e){$('summary').textContent='Demo engine error: '+e.message;$('sealState').textContent='FAIL CLOSED';$('effectMatch').textContent='FAIL'}finally{btn.disabled=false;btn.innerHTML='INVESTIGATE <span>↗</span>'}}
initMap();$('runBtn').addEventListener('click',run);document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{$('query').value=b.dataset.q;run()}));
